name: Release

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NEW_VERSION: ''
      RELEASE_NOTES_PATH: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update package version
        run: |
          pnpm update:version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update changelog
        run: |
          pnpm update:changelog
          echo "RELEASE_NOTES_PATH=.RELEASE_NOTES.md" >> $GITHUB_ENV

      - name: Commit & Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add package.json pnpm-lock.yaml CHANGELOG.md
          git commit -m "chore: release v${{ env.NEW_VERSION }}"
          git tag v${{ env.NEW_VERSION }} -m "Release ${{ env.NEW_VERSION }}"
          git push origin HEAD v${{ env.NEW_VERSION }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: v${{ env.NEW_VERSION }}
          body_path: ${{ env.RELEASE_NOTES_PATH }}
          draft: false
          prerelease: false
