name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bump version and create tag
        id: bump_version
        run: |
          pnpm update:version

          NEW_VERSION=$(node -p "require('./package.json').version")

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a v$NEW_VERSION -m "chore: release v$NEW_VERSION"
          git push origin v$NEW_VERSION

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update changelog
        run: |
          pnpm update:changelog

          git add CHANGELOG.md
          git commit -m "chore: update changelog for v$NEW_VERSION"
          git push origin main

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
